### ISSUE TITLE
Add support for Python 3.14

### ISSUE THREAD

**Issue by afuetterer** [afuetterer/python-re3data#298]
Python 3.14 is scheduled for 10/2025.

Ref: https://devguide.python.org/versions/#supported-versions

**Comment by afuetterer** [comment]
Let's begin with:

```yaml
- uses: actions/setup-python@v5
    with:
      python-version: '3.14-dev'
```
